### ISSUE TITLE
"k is not defined" error when selecting "Check Update" in Foundry 074

### ISSUE THREAD

**Issue by Gildashard** [foundry-vtt-community/tables#11]
![Image 14](https://user-images.githubusercontent.com/59094969/95996777-ad91dc00-0df8-11eb-8a3d-0dffbbabc2af.png)

**Comment by bekriebel** [comment]
Confirmed with FVTT v0.7.5 as well. Also, only version 0.6 of the module is installed because of this line in the module.json file, which may be part of the problem: https://github.com/foundry-vtt-community/tables/blob/5fb230b353ca6c33ddd7c343ba779f0e251a66ad/module.json#L25

**Comment by NirodhaAvidya** [comment]
Confirmed module only installs v0.6.
Foundry v0.7.5
Uninstalled then reinstalled module
Version remains v0.6

**Comment by AnthonyVadala** [comment]
This should now be resolved, sorry about the delay.

**Comment by pillarsdotnet** [comment]
Confirmed problem still exists in v0.7.5 as of today.
