### ISSUE TITLE
Item - Talisman of Ultimate Evil

### ISSUE THREAD

**Issue by Wade0004** [foundry-vtt-community/tables#13]
Small issue - the Talisman of Ultimate Evil states in your description that it must be attuned by a good alignment character, but I'm fairly certain the actual item requires an evil character for attunement.

THANKS!

**Comment by AnthonyVadala** [comment]
Looks like this is an issue with the official Foundry VTT SRD item description, so unfortunately this isn't something I can fix. 

Would you mind reporting this to Atropos using the bug report form [here](https://gitlab.com/foundrynet/foundryvtt/-/issues/new?issue%5Bassignee_id%5D=&issue%5Bmilestone_id%5D=) that way he can get that updated for everyone?
