### ISSUE TITLE
Forge and Foundry Hub list 0.9 as the most recent module version

### ISSUE THREAD

**Issue by chklein1** [foundry-vtt-community/tables#15]
The version of Foundry Community Tables listed at https://www.foundryvtt-hub.com/package/foundry_community_tables, and hosted on https://forge-vtt.com/bazaar, is 0.9 instead of the newer 0.14.

**Comment by AnthonyVadala** [comment]
This has been corrected by changing how the Foundry VTT Community Macros/Tables are versioned.

**Comment by chklein1** [comment]
Confirmed fixed - thanks!
