### ISSUE TITLE
Some items in the Common Loot table don't exist in the dnd5e.items compendium 

### ISSUE THREAD

**Issue by Seamonster73** [foundry-vtt-community/tables#17]
I'm guessing I may be missing something here as I'm surprised this hasn't come up before, but it looks like some of the items in the 'FVTT Community Tables 5E -> Common Loot' don't match (or in some cases don't exist) in the dnd5e.items compendium.

For example:

- Censor (named 'Cens**e**r' in the compendium)
- Gaming Set (Doesn't exist in the compendium)
- Gaming Set of Dice (Just called 'Dice' in the compendium)
- All of the Gaming Sets either have name mismatches or do not exist
- Same with the 'Musical Instrument' entries. In the compendium they are named as 'Bagpipes' instead of 'Musical Instrument: Bagpipes'
- Some tools seem to have issues - e.g. Thieves tools

A quick way to see which ones are broken is to import the table, open it, then click Update without having made any changes. Afterwards, scroll through the table and you'll see several entries are now blank, as it can't find them in the compendium.

This causes issues/errors with other modules that reference rolltables. 

Edit: I should mention I have manually fixed the table at my end if that's of any use! I'm not really up to speed on Github so don't know how to check out and make a pull request etc, but I've exported the 'fixed' version and attached it here if it helps
[fvtt-RollTable-common-loot.json.zip](https://github.com/foundry-vtt-community/tables/files/8041556/fvtt-RollTable-common-loot.json.zip)
.

**Comment by AnthonyVadala** [comment]
I have updated the table using your provided .zip file in v9.3
