### ISSUE TITLE
Request to Update Module to Foundry VTT v11

### ISSUE THREAD

**Issue by brunocalado** [foundry-vtt-community/tables#18]
Firstly, I would like to express my gratitude for your valuable contribution in developing this module for Foundry VTT. It has greatly enhanced my gaming experience.

I am reaching out to kindly request an update for your module to be compatible with the latest version of Foundry VTT, v11. As a passionate user of both Foundry VTT and your module, I am eagerly looking forward to enjoying the new features and improvements introduced in the latest version.

I understand that updating a module can be a time-consuming process, and I genuinely appreciate your effort and dedication in maintaining and improving it. Your work is highly valued by the Foundry VTT community.

If there is anything I can do to support you in this update process, such as providing feedback, testing, or any other assistance, please do not hesitate to let me know. I am more than willing to contribute to the success of your module.

Thank you for considering my request. I truly believe that updating your module to Foundry VTT v11 will greatly benefit the community and enhance the overall gaming experience for users. I am eagerly looking forward to the updated version.

**Comment by AnthonyVadala** [comment]
This module has been updated to v11.0 adding support for Foundry VTT v11
