### ISSUE TITLE
Request for Assistance: Issue with "Foundry VTT Tables Repository" Module Installation

### ISSUE THREAD

**Issue by brunocalado** [foundry-vtt-community/tables#19]
I hope this message finds you well. I am writing to seek assistance regarding an error I encountered while attempting to install the "Foundry VTT Tables Repository" module.

Description of the Issue:
Upon attempting to install the "Foundry VTT Tables Repository" module through the Foundry VTT module manager, I encountered an error message. The installation process did not complete successfully.

![image](https://github.com/foundry-vtt-community/tables/assets/4999783/beaa27c0-c379-4a64-a766-6c546e8699cd)

FetchError: An unexpected error occurred when downloading file https://github.com/foundry-vtt-community/tables/archive/v11.0.zip: request to https://codeload.github.com/foundry-vtt-community/tables/zip/refs/tags/v11.0 failed, reason: connect ETIMEDOUT 20.201.28.149:443
    at ClientRequest.<anonymous> (file:///C:/Users/Bruno/Documents/VTT/fvtt11/resources/app/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
fetch @ foundry.js:67697
setup.js:3452 Error: ENOENT: no such file or directory, open 'C:\Users\Bruno\Documents\VTT\FoundryVTT\Data\modules\foundry_community_tables.zip'
error @ setup.js:3452

**Comment by AnthonyVadala** [comment]
Looking at the error log it looks like there was a connection issue to GitHub itself when you were trying to install the module.

I did do some testing to make sure the module installs currently on both v11 and v9 - v10 from the module browser after you submitted this issue and I didn't encounter any errors.

Do you have any issues installing other modules hosted on GitHub from the module browser?
What version of Foundry VTT are you trying to install this module on?

**Comment by brunocalado** [comment]
worked, thank you
![image](https://github.com/foundry-vtt-community/tables/assets/4999783/7a5cd1ad-f91b-48e6-819d-1227ed81e613)
