### ISSUE TITLE
DND Beyond Extractor no longer seems to work

### ISSUE THREAD

**Issue by Nezarbek** [foundry-vtt-community/tables#21]
When attempting to use the DND Beyond Extractor, the generated file does export useful data. The title of the table seems to include items names and details for the wrong tables, and the actual table itself is just prices and weights with no item name. I tested this with the Other Adventuring Gear table (df00a6dc-2574-46f8-a0b7-1776040ae6e2) from DDB, and the title it gave me was for the ammunition table.
[console.json](https://github.com/foundry-vtt-community/tables/files/13624907/console.json)

**Comment by AnthonyVadala** [comment]
Removed script as it was broken and KaKaRoTo's Beyond 20 extension allows directly rolling from DnD Beyond tables.
